apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: NPM_CONFIG_USERCONFIG
            value: /tekton/home/npm/.npmrc
          image: uses:q1323829945/my-jx3-pipeline-catalog/tasks/javascript-ui-nginx/release.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          volumeMounts:
          - mountPath: /tekton/home/npm
            name: npmrc
          workingDir: /workspace/source
        steps:
        - image: uses:q1323829945/my-jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            date +%s-SNAPSHOT > VERSION
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 512Mi
        - name: npm-publish
          env: 
          - name: NPM_URL
            value: http://nexus.jx.svc.cluster.local:80/repository/
          - name: NPM_REGISTRY_RELEASES
            value: npm-releases
          - name: NPM_REGISTRY_SNAPSHOTS
            value: npm-snapshots
          - name: NPM_USERNAME
            value: admin
          - name: NPM_PASSWORD
            value: admin123
          - name: NPM_CUSTOMER_CONFIG
            value: .lighthouse/jenkins-x/.npmrc
          - name: NPM_CONFIG_USERCONFIG
            value: /workspace/source.lighthouse/jenkins-x/.npmrc
          name: npm-publish
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            registry=$NPM_URL
            if [[ "$VERSION" =~ ^.*-SNAPSHOT$ ]]; then 
              registry=$NPM_URL$NPM_REGISTRY_SNAPSHOTS/
            else 
              registry=$NPM_URL$NPM_REGISTRY_RELEASES/
            fi
            echo "the registry is $registry"
            apt-get update -y && apt-get install curl -y
            source .lighthouse/jenkins-x/publish.sh -r $registry -u $NPM_USERNAME -p $NPM_PASSWORD
            cat .lighthouse/jenkins-x/.npmrc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
