apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "pr"
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  postsubmits:
  - name: mydev
    context: "mydev"
    source: "dev.yaml"
    - ^.*-dev$
    branches:
  - name: snapshot
    context: "snapshot"
    source: "snapshot.yaml"
    branches:
    - ^.*-snapshot$
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - ^.*-release$
